### ISSUE TITLE
Full score is 120 not 130?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/pana#975] opened 2021-10-06 12:04 UTC
For example, here it is 130 points: https://pub.dev/packages/connectivity_plus/score `We analyzed this package on Oct 6, 2021, and awarded it 130 pub points (of a possible 130)`

But in my case I get:

```
(base) ➜  frb_dart git:(master) ✗ pana --no-warning --line-length 120 --exit-code-threshold 0
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart --version`...
INFO       Running `flutter --no-version-check --version --machine`...
INFO       Running `git rev-parse --show-toplevel`...
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart pub upgrade --verbose`...
INFO       Analyzing package...
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart analyze --format machine lib`...
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart format --output=none --set-exit-if-changed --line-length 120 /private/var/folders/pd/mpc7mwfj36ndyr9xbnnzk_s80000gn/T/pana_SxonkZ/frb_dart/lib`...
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart pub get .`...
INFO       Running `/Users/tom/opt/flutter/bin/cache/dart-sdk/bin/dart pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...

## ✓ Follow Dart file conventions (20 / 20)
### [*] 10/10 points: Provide a valid `pubspec.yaml`


### [*] 5/5 points: Provide a valid `README.md`


### [*] 5/5 points: Provide a valid `CHANGELOG.md`


## ✓ Provide documentation (10 / 10)
### [*] 10/10 points: Package has an example

* Found example at: `example/main.dart`

## ✗ Support multiple platforms (10 / 20)
### [~] 10/20 points: Supports 1 of 2 possible platforms (**native**, js)


Consider supporting multiple platforms:

<details>
<summary>
Package not compatible with runtime js
</summary>

Because:
* `package:flutter_rust_bridge/flutter_rust_bridge.dart` that imports:
* `package:flutter_rust_bridge/src/basic.dart` that imports:
* `package:flutter_rust_bridge/src/utils.dart` that imports:
* `dart:isolate`
</details>

## ✓ Pass static analysis (30 / 30)
### [*] 30/30 points: code has no errors, warnings, lints, or formatting issues


## ✓ Support up-to-date dependencies (20 / 20)
### [*] 10/10 points: All of the package dependencies are supported in the latest version

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`lints`]|`^1.0.1`|1.0.1|1.0.1|
|[`meta`]|`^1.3.0`|1.7.0|1.7.0|

To reproduce run `dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides`.

[`lints`]: https://pub.dev/packages/lints
[`meta`]: https://pub.dev/packages/meta


### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs


## ✓ Support sound null safety (20 / 20)
### [*] 20/20 points: Package and dependencies are fully migrated to null safety!


Points: 110/120.
```

The full score is 120 not 130 here...

**Comment by isoos** [comment] 2021-10-06 13:15
`pana` and `pub.dev` differs a slightly bit, e.g. pub.dev runs a modified version of `dartdoc` that exposes the documentation coverage metrics, which `pana` doesn't have access to. The coverage is 10 points max, that's the difference you see there.

As the core issue is duplicate of #870, I'll close this for now.

**Closed by isoos** 2021-10-06 13:15 UTC

**Comment by fzyzcjy** [comment] 2021-10-06 13:16
thanks!
