### ISSUE TITLE
pana on pub is using the wrong version of dart

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/pana#1392] opened 2024-08-03 23:03 UTC
I'm on latest stable channel in flutter using `flutter create -t foo` which is creating these environment constraints

```yaml
environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"
```

however, pana on pub appears to be stuck on `3.4.3` which is making static analysis fail.

short version is my expectation is that pub always uses the latest version of dart (or later) compared to flutter stable branch

here's the package in question https://pub.dev/packages/lukehog/score

more context: https://x.com/luke_pighetti/status/1819868903377449019

**Comment by lukepighetti** [comment] 2024-08-03 23:03
not sure if this is the right repo to make this issue!

**Comment by isoos** [comment] 2024-08-04 17:28
Duplicate of https://github.com/dart-lang/pub-dev/issues/7888, closing it here.

**Closed by isoos** 2024-08-04 17:28 UTC
