### ISSUE TITLE
No valid SDK. (-20 points)

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/pana#632] opened 2020-04-11 12:32 UTC
I have next problems with my package that contains only linter rules and no any dart code.
But I have two problems 
No valid SDK. (-20 points)
Make sure dartdoc successfully runs on your package's source files. (-10 points)

What I should do to fix them?

My package [strict_dart](https://pub.dev/packages/strict_dart)

**Comment by isoos** [comment] 2020-04-11 12:46
@vr19860507: thanks for reporting, this is a known issue, sorry for that. We don't have a timeline when this will be fixed, hopefully soon. Duplicate of #604. Closing.

**Comment by vr19860507** [comment] 2020-04-11 12:46
Thank you.

**Closed by isoos** 2020-04-11 12:46 UTC
