### ISSUE TITLE
Validation fails for mailto Urls

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pana#761] opened 2020-08-05 14:07 UTC
From [Ray Li on twitter](https://twitter.com/RayLiVerified/status/1283429250364772352):

![image](https://user-images.githubusercontent.com/13644170/89422500-b8aff800-d735-11ea-83a0-e89127cf8726.png)

**Comment by isoos** [comment] 2020-08-05 16:17
Duplicate of #729
Fixed in https://github.com/dart-lang/pana/pull/730

**Closed by isoos** 2020-08-05 16:17 UTC
