### ISSUE TITLE
Use pub to download package, to have checksum validation of download

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#509] opened 2019-02-11 09:43 UTC
If the [`x-goog-hash`](https://cloud.google.com/storage/docs/xml-api/reference-headers#xgooghash) header is present when downloading a file, we should validate md5 and crc32.

This could help mitigate corrupted downloads, with HTTPS I think this can only happen if the connection is broken is an unfortunate way that leaves the client with a partial download. So checking content-length might be enough -- I'm not sure if we're doing this, from a quick look I couldn't find where it happens. But it's quite possible it does happen somewhere :)

**Comment by sigurdm** [comment] 2024-01-25 09:53
We should probably just use `pub unpack` (when finished) or make a dummy-package depending on the package, and use `pub get` to download it.

**Comment by sigurdm** [comment] 2024-01-25 09:54
Closing as duplicate of https://github.com/dart-lang/pana/issues/1170

**Closed by sigurdm** 2024-01-25 09:54 UTC
Labels: type-enhancement, P3
