### ISSUE TITLE
Don't decrease scoring, if a package does only support a single platform

### ISSUE THREAD

**Issue by Blimster** [dart-lang/pana#781] opened 2020-09-04 14:10 UTC
Currently, a package gets a decreased score, if it does not support all platforms. This does not make sense for packages, that only support a specific platform by intention. An example is the package "angular". Angular is made for the web and it should not get a decreased score, because it does not support the native platform.

There should be a way to list the supported platforms in the pubspec.yaml. The score should then only be decreased, if the list of platforms to be supported does not match the list of actually supported platforms by its package dependencies.

**Comment by sigurdm** [comment] 2020-09-07 12:39
I think this is more or less a duplicate of: https://github.com/dart-lang/pana/issues/720

**Closed** 2020-11-23 22:58 UTC
