### ISSUE TITLE
Line Length is forced to 80

### ISSUE THREAD

**Issue by nstrelow** [dart-lang/pana#822] opened 2021-01-02 21:44 UTC
I would like to use 120 as a line length, but I am forced to format everything to 80.

Similar issue in dart-lang:
https://github.com/dart-lang/pub-dev/issues/3041

**Comment by sigurdm** [comment] 2023-10-12 09:10
Closing this as duplicate of https://github.com/dart-lang/pub-dev/issues/3041

**Closed by sigurdm** 2023-10-12 09:10 UTC
