### ISSUE TITLE
Error: Maintain an example

### ISSUE THREAD

**Issue by brianegan** [dart-lang/pana#408] opened 2018-09-16 12:59 UTC
Hey there! Question for y'all: I have two examples inside the `example` folder of my project, but pana is reporting: "Maintain an example. None of the files in your example/ directory matches a known example patterns. Common file name patterns include: main.dart, example.dart or you could also use flutter_redux.dart."

Could you please help me understand what pana is looking for? Should there only be one example inside the example folder (If so, any pointers on the recommended folder structure for multiple examples would be great)? I have two files named `main.dart` within subdirectories of the `example` folder, but neither seems to satisfy this requirement.

Package: https://pub.dartlang.org/packages/flutter_redux#-analysis-tab-
Repo: https://github.com/brianegan/flutter_redux

**Comment by isoos** [comment] 2018-09-16 13:33
Also related: https://github.com/dart-lang/pub-dartlang-dart/issues/1434

**Comment by isoos** [comment] 2018-09-17 08:06
I don't recall where it was discussed, but at one point we have also considered that if there is a `example/README.md`, we'd rather display that file, with the assumption that it will contain detailed information about the different examples.

I'll add that exception to the suggestions.

**Comment by mit-mit** [comment] 2018-09-21 12:34
Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/1434

**Closed by mit-mit** 2018-09-21 12:34 UTC

**Comment by isoos** [comment] 2018-10-30 11:58
@brianegan: pub now recognizes `example/readme.md` and if you have it, it will be shown on the example tab.
