### ISSUE TITLE
Output is confusing for platforms with 1 supported platform

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pana#720] opened 2020-07-09 16:14 UTC
If a Flutter package has 1 supported platform, the output is: "
0/20 points: Supports 0 of 3 possible platforms (iOs, Android, Web) "
https://pub.dev/packages/workmanager/score

I think we need to update the conditional in https://github.com/dart-lang/pana/blob/master/lib/src/create_report.dart#L794 to something like:

```dart
if (officialTags.length == 0) {
        subsection = _Subsection(
            'No supported platforms identified',
            issues,
            0,
            20,
            _Status.bad);
} else if (officialTags.length == 1) {
        subsection = _Subsection(
            'Support 2 or more of 3 possible platforms ($platforms)',
            issues,
            0,
            20,
            _Status.bad);

```

**Comment by timsneath** [comment] 2020-07-15 16:51
I'm still not sure how I feel about this criterion. It would be interesting to see a sample of packages that are dinged for not supporting two or more platforms to validate that we're driving the right behavior. Should an Apple Pay package be dinged for not supporting Android, for instance?

**Comment by artob** [comment] 2020-08-02 03:11
As the author of a (necessarily) [Android-only package](https://pub.dev/packages/flutter_android), the current scoring does not feel right:

<img width="849" alt="Screen Shot 2020-08-02 at 06 03 54" src="https://user-images.githubusercontent.com/4963/89114521-0c94b580-d486-11ea-8426-c97c2bd78a99.png">

Why should a platform-specific package--maintained to a high standard--get penalized in this way, never being able to reach a 100% score?

I would respectfully suggest that it doesn't make sense to deduct -20 points from packages that have declared they only support a single platform. Those are more likely than not going to actually be tied to a particular platform for some good reason.

However, if a package declares support for two or more platforms, then it is inherently capable of being a cross-platform package and it would thus be desirable for its maintainers to endeavor to add support for all Flutter platforms over time.

**Comment by artob** [comment] 2020-08-02 03:19
I should perhaps note that my package _didn't_ get penalized in this way until changing to the new `flutter: plugin: platforms:` scheme in `pubspec.yaml`. By all means, feel free to penalize packages which didn't adopt the new scheme, since their platform support is ambiguous.

**Comment by isoos** [comment] 2020-08-03 08:55
@artob: A few notes on the scoring and ranking here: https://github.com/dart-lang/pub-dev/issues/3862#issuecomment-667896811

> I should perhaps note that my package didn't get penalized in this way until changing to the new flutter: plugin: platforms: scheme in pubspec.yaml. By all means, feel free to penalize packages which didn't adopt the new scheme, since their platform support is ambiguous.

/cc @jonasfj @sigurdm ?

**Comment by sigurdm** [comment] 2020-08-03 09:24
> Why should a platform-specific package--maintained to a high standard--get penalized in this way, never being able to reach a 100% score?

I am also uneasy about this. @mit-mit explains (as I understand, otherwise please correct me) that this is because for the end-user it is preferable to use a package with broad support. Your package will get the same scoring as any other package for the same platform-specific task.

For example https://pub.dev/packages/flutter_android has support for the android face-recognition apis (among many other things). That might be nice if you want very tight control with how you use those apis on android, but they make it hard to do face-recognition across platforms. Something like https://pub.dev/packages/flutter_camera_ml_vision might be preferable for a task like that.

The pub-points should be interpreted as "How useful is this package to the end user", not "how good is the maintainer doing the job of maintaining the package".
And some categories of packages have a less broad appeal. This is of course an interpretation - and might not satisfy everyone (I also feel uneasy about it).

> I should perhaps note that my package didn't get penalized in this way until changing to the new flutter: plugin: platforms: scheme in pubspec.yaml. By all means, feel free to penalize packages which didn't adopt the new scheme, since their platform support is ambiguous.

At this point we probably should give less points to packages using the old platform declarations. @mit-mit do you have an opinion?

**Comment by artob** [comment] 2020-08-03 09:43
> > Why should a platform-specific package--maintained to a high standard--get penalized in this way, never being able to reach a 100% score?
> 
> I am also uneasy about this. @mit-mit explains (as I understand, otherwise please correct me) that this is because for the end-user it is preferable to use a package with broad support. Your package will get the same scoring as any other package for the same platform-specific task.
> 
> For example https://pub.dev/packages/flutter_android has support for the android face-recognition apis (among many other things). That might be nice if you want very tight control with how you use those apis on android, but they make it hard to do face-recognition across platforms. Something like https://pub.dev/packages/flutter_camera_ml_vision might be preferable for a task like that.

Sure, in the case of a _potentially_ platform-agnostic feature such as face detection, that's clear. But that's not the raison d'etre for most platform-specific functionality.

Rather, [flutter_android](https://github.com/drydart/flutter_android)--and similar plugins for other platforms--expose platform APIs which _aren't_ and _cannot_ be cross-platform, but which somebody building a Flutter app targeting Android (among other platforms) would like to utilize so as to provide the best user experience in some aspect or another--without themselves having to write the respective Java code in that app, and every other app, that needs it.

That's a perfectly respectable use case for a Flutter package, I'd dare say, and it seems counterproductive to penalize it.

**Comment by isoos** [comment] 2020-08-03 09:49
(moving my comment from the other discussion here)

Granting more pub points for packages the support multiple platform is a tough choice: we want to promote multi-platform packages, at the same time we are aware that package with narrow scope (e.g. build-only, JS-only, Android-only, dart:ffi-based interop-only) will get fewer points. However, this allows a uniform, easy-to-understand score, which can be applied to all packages. Presumably, packages with similar constraints will get similar scores (as they are not able to support the other platforms the same way), and their relative rank in the package listing is unaffected by the uniform scoring rules.

The alternative would be to introduce different categories (there would be many more than the 4 listed here), each of them granted points with different rules. While the technical means to have separate categories with separate score ranges is available, the scoring system is not only for the package author, it is for the potential user of the package too. Besides the difficulties to communicate why a specific package gets that category and score (or multiple categories with multiple scores, why the overlap, etc.), the problem is with the difference of the score itself.
When browsing and searching for a package, we'd need to display scores that are comparable and meaningful in a consistent way. E.g. mixing an Android-specific score with a build-system-specific score on the same result page would be very confusing and would not provide much value.

On the plus side of the single score, we do have a mechanism to differentiate the ranking for specific use cases: if the search scope is specific (to an SDK now, maybe to a runtime/platform later), we do have specificity-ranking. E.g. if you select the Dart SDK as a filter, packages that support only the Dart SDK will rank higher compared to the ones that support both Dart and Flutter.

**Comment by jonasfj** [comment] 2020-08-03 15:25
> At this point we probably should give less points to packages using the old platform declarations. @mit-mit do you have an opinion?

IMO, this would be uncontroversial. We could add this to our checks for `pubspec.yaml` which grants 5 points.

**Comment by jonasfj** [comment] 2020-08-03 16:48
> That's a perfectly respectable use case for a Flutter package, I'd dare say,

I think there is resounding agreement here :D

At the same time, Flutter is a cross-platform toolkit, hence, it seems reasonable that users would prefer cross-platform packages -- when it is possible.

> and it seems counterproductive to penalize it.

hmm, our hope was that we would be moving away from penalizing towards rewarding good behavior.
I suppose that is a subtle difference.. I think we should let the new system grow on us a little, and if it continues to cause confusion we might need to reconsider it.

**Comment by timsneath** [comment] 2020-08-03 17:03
FWIW, your concern resonated with me, @artob -- since I have a very similar single-platform package to yours, [targeting Windows](https://pub.dev/packages/win32), that is "penalized" in this way. It's slightly annoying to not score 100% when a package is designed to target one platform. The intention, as @jonasfj has indicated, is to think of points as being _granted_, rather than _subtracted_ -- although we may still need to tweak the text on the score page to suggest that better. 

In practice, I suspect this is not a real concern for anyone perusing our packages, so long as a "not-perfect" score doesn't impact things like search. If your package has high popularity and otherwise scores highly, it's going to do at least as well as any other rival package that targets a single platform.

**Comment by jakemac53** [comment] 2020-08-04 15:26
I noticed today that my code generator package is also dinged because of this, and I will admit it makes me irrationally angry. I have done nothing wrong, and I have absolutely no recourse for the situation.

Code generators are only designed to run on the VM, and that makes a lot of sense. They are a development tool only. Punishing users that have no recourse is not IMO the right thing to do.

**Comment by maks** [comment] 2020-08-11 09:43
I'm here for similar reasons but in my case, my package is a static site generator, so similar I guess to a build tool, though I also actually use dart2native to also create native executables for linux, macos and windows so its definitely supporting all the platforms it makes sense to do so.

I'm late to this discussion, but  my 2c: it seems that this is a rather Flutter-centric (plugins are mentioned several times in the discussion here) scoring rule being applied to all packages on pub where not all packages are actually plugins intended for use with Flutter.

**Comment by fatherOfLegends** [comment] 2020-11-13 06:02
My team maintains a package for testing. (golden_toolkit) I noticed our package and all other packages that depend on flutter_test are docked points and filtered out of search when marking web as your platform because they are not compatible with the web target but these package work just fine for an app targeting the web when used as a dev dependency like they are intended. I am less concerned about the overall score and more concerned about developers overlooking the package due to misinformation.

**Comment by jonasfj** [comment] 2020-11-20 13:33
>  (golden_toolkit) I noticed our package and all other packages that depend on flutter_test are docked points and filtered out of search when marking web as your platform because they are not compatible with the web target but these package work just fine for an app targeting the web when used as a dev dependency like they are intended.

Please file a separate issue, this seems like an orthogonal concern. The same argument applies to a code-generation tool, it doesn't work on the web, but you can use it to make code for the web.

**Comment by fatherOfLegends** [comment] 2020-11-20 20:16
Created #808

**Comment by sigurdm** [comment] 2023-11-23 09:44
Closing as obsolete. We no longer give lower scores when few platforms are supported

**Closed by sigurdm** 2023-11-23 09:44 UTC
