### ISSUE TITLE
Separate top level imports should not cause platform issues

### ISSUE THREAD

**Issue by grouma** [dart-lang/pana#511] opened 2019-02-15 18:32 UTC
`package:sse` is a good example in which it has a top level `client` folder that imports `html`. It also has a top level `server` folder which imports `io`. This should be allowed and not cause the error: `Fix platform conflicts. (-20 points)`

**Comment by jonasfj** [comment] 2019-02-18 12:25
@isoos, could this because the `sse` package doesn't have an `sse.dart` file?

**Comment by isoos** [comment] 2019-02-18 12:35
This has nothing to do with the lack of top-level `sse.dart` file, and it is not caused by the two separate top-level libraries. The report says: `Conflicting libraries: package:sse/client/sse_client.dart (components: html, isolate).`

The `dart:html` is imported by the `sse_client.dart` itself, and `dart:isolate` is imported by the `stream_channel` package, in the `isolate_channel.dart`: https://github.com/dart-lang/stream_channel/blob/master/lib/stream_channel.dart#L15

As `dart:isolate` is no longer supported on the web, this is the cause of the platform conflict.

**Comment by jonasfj** [comment] 2019-02-18 12:56
In that case let's close this issue.

**Closed by jonasfj** 2019-02-18 12:56 UTC
