### ISSUE TITLE
Provided content does not align with expectations.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#917] opened 2021-07-05 13:53 UTC
```
pub.analyzer.pana: Failed (v0.17.0) - grid_world/0.1.7

Error:
    Invalid argument(s): Provided content does not align with expectations.
    `No dart files found at: /tmp/pana_VZVNQW/bin`

Stack:
    #0      parseCodeProblem (package:pana/src/code_problem.dart:65:5)
    #1      PackageContext.staticAnalysis.<anonymous closure> (package:pana/src/package_context.dart:119:25)
    #2      MappedIterator.moveNext (dart:_internal/iterable.dart:389:20)
    #3      WhereIterator.moveNext (dart:_internal/iterable.dart:435:22)
    #4      SetMixin.addAll (dart:collection/set.dart:57:23)
    #5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)
    #6      Iterable.toSet (dart:core/iterable.dart:376:21)
    #7      PackageContext.staticAnalysis (package:pana/src/package_context.dart:121:14)
    <asynchronous suspension>
    #8      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
    
```

**Comment by isoos** [comment] 2021-07-05 15:09
I think this has been fixed at `HEAD`, as I can't reproduce. Not sure if it was fixed in the last release too.

**Comment by isoos** [comment] 2021-07-19 17:50
This is no longer present on pub.dev.

**Closed by isoos** 2021-07-19 17:50 UTC
Labels: Type: bug
