### ISSUE TITLE
dart run pana --hosted googleapis_auth fails to find any platforms

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#824] opened 2021-01-15 11:53 UTC
> ## ✗ Support multiple platforms (0 / 20)
> ### [x] 0/20 points: Supports 0 of 2 possible platforms (native, js)

I also checked the JSON output, there is no tags.

**Comment by jonasfj** [comment] 2021-01-15 15:15
Probably same issue with https://pub.dev/packages/webdriver

**Comment by sigurdm** [comment] 2021-01-20 09:02
Adding some debug prints reveals the issue:
```
Package not compatible with sdk dart using runtime native-aot, Because:
* `package:googleapis_auth/auth_browser.dart` that imports:
* `package:googleapis_auth/src/oauth2_flows/implicit.dart` that imports:
* `dart:js`)
Package not compatible with sdk dart using runtime native, Because:
* `package:googleapis_auth/auth_browser.dart` that imports:
* `package:googleapis_auth/src/oauth2_flows/implicit.dart` that imports:
* `dart:js`)
Package not compatible with sdk dart using runtime js, Because:
* `package:googleapis_auth/auth_io.dart` that imports:
* `package:googleapis_auth/src/oauth2_flows/metadata_server.dart` that imports:
* `dart:io`)
```

We should find a way to have that explanation bubble up to the output. There is a comment
```
        if (violation != null) {
          // This is reported elsewhere
        } else {
```

It seems that is lying.

**Comment by isoos** [comment] 2021-08-05 09:44
https://github.com/dart-lang/pana/pull/929 adds a bit more information to the report. Notes from the code review to be addressed later:
- > `Consider supporting these prerelease platforms:`
  > This line reads weirdly...
- > `Package not compatible with SDK dart`
  > We should end with a full stop `.`.
- > `Because it is not compatible with any of the supported runtimes: native-aot, native, js`
  > We should end with a full stop `.`.
  > We really should document somewhere what this means, and link. As the package author there is not much to go on.

**Comment by isoos** [comment] 2021-08-05 12:40
In the case of `webdriver 3.0.0` we don't report any platform compatibility because:
- it doesn't have a single top-level library (`webdriver.dart`), but multiple ones
- `*_io.dart` imports `dart:io`, `*_html` imports `dart:html`, and as we iterate through the platforms, each of them is blocked by some of the libraries

**Comment by sigurdm** [comment] 2021-08-05 12:57
> it doesn't have a single top-level library (webdriver.dart), but multiple ones
*_io.dart imports dart:io, *_html imports dart:html, and as we iterate through the platforms, each of them is blocked by some of the libraries

Ideally we should be able to present this information. (and/or even allow different top-level libraries to have different support bases).

**Comment by isoos** [comment] 2021-08-13 06:57
> Ideally we should be able to present this information. (and/or even allow different top-level libraries to have different support bases).

Exposing the debug information seems to work with the current release:
![image](https://user-images.githubusercontent.com/4778111/129317083-f5fe5814-2217-43a0-b789-2d4fd8249b64.png)

**Comment by sigurdm** [comment] 2021-08-13 07:10
Now the question is - do we want to allow for libraries to be multi-platform in this way? - they clearly work on some platforms - it is just going to be complicated to communicate this in a coherent manner...

**Comment by isoos** [comment] 2021-08-13 08:21
One idea to do this is following the patterns used by package authors:
- if a library name ends with `_io.dart` (`_server.dart`, `_console.dart`) then we care only about IO-related rules...
- if a library name ends with `_html.dart` (`_js.dart`, `_web.dart`, `_browser.dart`) then we care only about web-related rules...

**Comment by sigurdm** [comment] 2023-11-09 10:04
We should confirm if this is still an issue

**Comment by isoos** [comment] 2023-11-09 10:22
Our analysis and report changed significantly since this was reported, closing. Please reopen if there is a recent reproduction of a similar issue.

**Closed by isoos** 2023-11-09 10:22 UTC
Labels: type-bug
