### ISSUE TITLE
Score reduced for static analysis but doing what is recommended makes package worse

### ISSUE THREAD

**Issue by Hixie** [dart-lang/pana#972] opened 2021-09-23 21:59 UTC
https://pub.dev/packages/rfw/score gives 20/30 for the static analysis section, and complains that some files are not formatted. However, formatting the files as recommended makes them less readable, for example it changes this:

```dart
    switch (type) {
      case _msLoop:
        return Loop(_readArgument(), _readArgument());
      case _msWidget:
        return _readWidget();
      case _msArgsReference:
        return ArgsReference(_readPartList());
      case _msDataReference:
        return DataReference(_readPartList());
      case _msLoopReference:
        return LoopReference(_readInt64(), _readPartList());
      case _msStateReference:
        return StateReference(_readPartList());
      case _msEvent:
        return EventHandler(_readString(), _readMap(_readArgument)!);
      case _msSwitch:
        return _readSwitch();
      case _msSetState:
        return SetStateHandler(StateReference(_readPartList()), _readArgument());
      default:
        return _parseValue(type, _readArgument);
    }
```

...to this:

```dart
    switch (type) {
      case _msLoop:
        return Loop(_readArgument(), _readArgument());
      case _msWidget:
        return _readWidget();
      case _msArgsReference:
        return ArgsReference(_readPartList());
      case _msDataReference:
        return DataReference(_readPartList());
      case _msLoopReference:
        return LoopReference(_readInt64(), _readPartList());
      case _msStateReference:
        return StateReference(_readPartList());
      case _msEvent:
        return EventHandler(_readString(), _readMap(_readArgument)!);
      case _msSwitch:
        return _readSwitch();
      case _msSetState:
        return SetStateHandler(
            StateReference(_readPartList()), _readArgument());
      default:
        return _parseValue(type, _readArgument);
    }
```

...which makes it harder to scan the switch statement, because one of the case statements now has a weird discontinuity where it doesn't match the style of the others.

There are even worse examples, for example it turns this:

```dart
    data.update('color', decodeDataBlob(Uint8List.fromList(<int>[
      0xFE, 0x52, 0x57, 0x44, // signature
      0x07, // data is a map
      0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // ...which has one key
      0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // ...which has five letters
      0x76, 0x61, 0x6c, 0x75, 0x65, // ...which are "value"
      0x02, // and the value is an integer
      0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // ...which is the number 2
    ])));
```

...into:

```dart
    data.update(
        'color',
        decodeDataBlob(Uint8List.fromList(<int>[
          0xFE, 0x52, 0x57, 0x44, // signature
          0x07, // data is a map
          0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, // ...which has one key
          0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, // ...which has five letters
          0x76, 0x61, 0x6c, 0x75, 0x65, // ...which are "value"
          0x02, // and the value is an integer
          0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
          0x00, // ...which is the number 2
        ])));
```

The worst is that it turns this:

```dart
    ArgumentDecoders.imageProviderDecoders['beepboop'] = (DataSource source, List<Object> key) {
      return MemoryImage(Uint8List.fromList(<int>[
        0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00,  0x01, 0x00, 0x80, 0xff, 0x00, 0xc0, 0xc0, 0xc0,
        0x00, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00,  0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x01, 0x00, 0x00, 0x02, 0x02, 0x44,  0x01, 0x00, 0x3b,
      ]));
    };
```

...into:

```dart
    ArgumentDecoders.imageProviderDecoders['beepboop'] =
        (DataSource source, List<Object> key) {
      return MemoryImage(Uint8List.fromList(<int>[
        0x47,
        0x49,
        0x46,
        0x38,
        0x39,
        0x61,
        0x01,
        0x00,
        0x01,
        0x00,
        0x80,
        0xff,
        0x00,
        0xc0,
        0xc0,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x21,
        0xf9,
        0x04,
        0x01,
        0x00,
        0x00,
        0x00,
        0x00,
        0x2c,
        0x00,
        0x00,
        0x00,
        0x00,
        0x01,
        0x00,
        0x01,
        0x00,
        0x00,
        0x02,
        0x02,
        0x44,
        0x01,
        0x00,
        0x3b,
      ]));
    };
```

It seems absurd to give a package with this "formatted" version a higher score than the much readable version it has now.

**Comment by isoos** [comment] 2021-09-24 15:39
I think we have two separate issues here:

1) whether pana / pub.dev should reward consistency across the ecosystem, and
2) whether the formatter provides a good output in special cases.

I think it is good to reward consistency, and we should continue doing it, and deal with the inevitable edge cases (and fix the underlying tools). In this case, (and also in others like https://github.com/dart-lang/dart_style/issues/1045), the formatter could be smarter about formatting and `int` list (be it bytes only or wider range of values).

Maybe we could have an annotation for `dartfmt` to not format the next statement in the code (similar to lint opt-outs)?

**Comment by Hixie** [comment] 2021-09-24 22:33
Given the number of places where the formatters makes poor choices in these files, it might be best to have a way to opt out the entire file. That's what we ended up doing in the repo where the package is hosted -- files that contain the magic string `// This file is hand-formatted.` are exempt from being formatted.

In general, I would suggest it's more valuable for us to reward readable files than blind consistency. Emerson's thoughts on the topic seem apropos here.

**Comment by sigurdm** [comment] 2022-02-10 10:02
I think we want to keep formatting a requirement for full points.

So discussions of formatter specifics should be taken in the dart-style issue tracker.

@mit-mit @munificent

**Comment by munificent** [comment] 2022-02-10 22:07
> I think we want to keep formatting a requirement for full points.

I don't. Penalizing package authors for not using dart_style puts *incredible* pressure on dart_style and me to produce output that satisfies every user out there.

There is a big difference between "Here's a tool we think makes the ecosystem easier to read and contribute to if we all agree to opt into it." and "If you don't run this tool, we will publicly tell everyone that your package is bad."

**Comment by isoos** [comment] 2022-02-10 22:39
> we will publicly tell everyone that your package is bad

I don't think that we present the scores and the result of the analysis in any way that would be judgmental or in bad faith. We try to provide useful information both to the users and to the author of the package, also, how they could improve their score.

But the target audience is not the author. Package analysis and public score serve the (future) users of the packages first and foremost. When one takes a package as a dependency (which is a risk for many reasons), they want to consider every possible signal about it, its maintenance and current state to certain (evergreen) standards. If anything, we need more signals and more sections to score, not fewer - it would likely reduce the anxiety about chasing the maximum score.

**Comment by Hixie** [comment] 2022-02-11 00:33
Without taking a position on this specific issue (I can see arguments on both sides):

> I don't think that we present the scores and the result of the analysis in any way that would be judgmental or in bad faith. 

I've definitely seen package authors do things they consider to be a net negative to their package because they want a higher score, and I presume that is because they view a higher score as leading to more usage because a lower score means their package is less good (more bad) than another otherwise-identical package with a higher score.

For example, if I cared deeply about usage of package:rfw, I would probably just run the formatter on it, so as to give it the highest possible score, even though that is not (IMHO, but maybe also objectively?) the best thing for the package readability. (I wouldn't be surprised if even Bob agreed with me about some of the cases we're talking about here... :-) )

(In fact, if I were chasing usage, I would probably consider doing something like running the formatter before uploading to pub, but not commit the formatted version to GitHub, which is probably a much worse outcome than not formatting the code...)

**Comment by mit-mit** [comment] 2022-02-11 09:46
Happy to have an overall discussion about this, so re-opening this to reflect that.

**Comment by munificent** [comment] 2022-02-17 23:38
I think part of the problem is that the score does two things at the same time:

1. It sends a signal to the package author about how well we feel their code fits into the Dart ecosystem (or at least how well we can automatically determine that it fits).
2. It sends a signal *publicly to other users of the package* about how good their package is.

The former is a helpful signal to encourage users sharing Dart code to follow what we believe are the best practices. The latter mixes that with an aspect of public shaming that worsens experience of receiving a bad score.

I'd like to encourage users to use the formatter, but rolling it into package scoring is a pretty big hammer. (I am certainly biased, though because. It makes my job harder when formatting affects package scoring because it makes the users who already hate the formatter even more angry at me.)

Maybe it's worth considering removing formatting from package scoring, but showing on the package page's sidebar as to whether or not it is auto-formatted. That way users that care about that can seek out packages that do it and users that don't care don't have to?

**Comment by mit-mit** [comment] 2022-02-21 09:01
>  The latter mixes that with an aspect of public shaming that worsens experience of receiving a bad score.

That is certainly not the goal, and I suspect subjective (I personally don't feel it does that, but totally understand that others may).

Do you feel this is special to the formatting component of the overall scoring mechanism?

> Maybe it's worth considering removing formatting from package scoring, but showing on the package page's sidebar as to whether or not it is auto-formatted.

That seems overly convoluted to me, and I think we'll end up having the same discussion about that sidebar at some point.

One option we might consider would be to move it to to the Admin tab (only shown to those that are owners of the package),  under a "Maintenance tips" section.

**Comment by munificent** [comment] 2022-02-22 19:33
> Do you feel this is special to the formatting component of the overall scoring mechanism?

I think it's true of any public scoring system overall (Twitter likes, Reddit upvotes, YouTube downvotes, etc.). I'm probably highly sensitive to formatting affecting the pub score because when that does upset users, they come to me to complain.

Also, many users have a deep emotional attachment to their preferred formatting style, so using formatting for package scoring can put them in a difficult bind where they don't want to use the formatter, but they also don't want to be publicly penalized for not using it.

**Comment by sigurdm** [comment] 2023-09-21 09:27
Do we still want to do anything here?

**Comment by sigurdm** [comment] 2024-01-25 09:46
I think we are keeping status quo here, and closing this issue.

I would like the formatter to be customizable enough that line-lengths and other oddities would not bother people.

**Closed by sigurdm** 2024-01-25 09:46 UTC
Labels: type-question
